### PR TITLE
ReflectionTypeRepository fix for ASP.NET Core

### PR DESCRIPTION
**Pull request by kurattila**
This PR fixes a bug in `Structurizr.Analysis.ReflectionTypeRepository`, resulting in an unhandled exception whenever an ASP.NET Core assembly is examined through reflection.

Unit test added, as well, to demonstrate the scenario where the fix is needed.

### CODE REVIEW

**Comment by simonbrowndotje** [comment]
Thanks!

**Comment by simonbrowndotje** [comment]
I've had to revert the PR as I can't get the Core.Reflections library to compile against netstandard2.0 ... I think this is why we left the project target as net452 and a Cecil version was created for .NET Core.

I will revisit this later when I have more time.

**Comment by kurattila** [comment]
What errors do you get when building against netstandard2.0? Maybe I can help here; I have always a successful build on VS2017, with .NET Core 2.0 dev tools installed.

**Comment by simonbrowndotje** [comment]
I get lots of errors related to methods missing from Type.

screen shot 2018-03-30 at 08 18 33

**Comment by kurattila** [comment]
The solution can lie in .NET versions. The [announcement of .NET 4.7.1](https://blogs.msdn.microsoft.com/dotnet/2017/10/17/announcing-the-net-framework-4-7-1/) claims that version 4.7.1 is the first one to have full, *built-in* support for .NET Standard 2.0. Please check if your registry entry of `Release` under `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full` says either `461308` or `461310` (they both indicate 4.7.1).
I have that version on 3 different machines and all of them build Structurizr.Reflection just fine.

**Comment by simonbrowndotje** [comment]
I have ```461308``` but still no joy.

screen shot 2018-03-31 at 09 32 54

screen shot 2018-03-31 at 08 44 43

screen shot 2018-03-31 at 08 42 55

**Comment by simonbrowndotje** [comment]
The version reported by the CLI is correct. Visual Studio is now doing an update, so hopefully this will fix the problem!

screen shot 2018-03-31 at 10 34 10

**Comment by simonbrowndotje** [comment]
My Visual Studio updates are failing for some reason, but I've managed to add support for .NET 4.7.1, which was a missing component in my VS installation. It's working now, and I've incorporated your change to the ```ReflectionTypeRepository``` class (I need to add some tests for the whole project, so I'll do that as a separate exercise). Thanks for your help with this! 👍

**Comment by kurattila** [comment]
My pleasure, I'm glad it works!

**Pull request merged**
