### PR TITLE
#47 Add new C4PlantUmlWriter with C4-PlantUML support

### PR DESCRIPTION
**Pull request by kirchsth**
- Add new C4PlantUmlWriter with C4-PlantUML support (issue #47)
- ModelItem returns a list of all tags via GetAllTag()
- RelationshipView support an additional list of tags which can be used in the diagram via ViewTags.
  RelationshipView.GetAllTag() returns a merged list of ViewTags and all Relationship tags
- Update relationship descriptions and technology in BigBankPlc example
- Update PlantUMLWriterTests and C4PlantUmlWriterTests that the expected text can be (simpler) reused as UML definition

### CODE REVIEW

**Comment by kirchsth** [comment]
Hi Simon, the "view tags" are a view specific extension like x and y in "ElementView". In my case I use it and add directions like up/down/left/right but it could be generic enough to add other view related information too.  And I (re-)used "tags" that I could even defined a common layout directly in the model and reuse it in all views (like person is on top of view). 
What would be your suggestion that I have something like "x,y". I think style would be wrong.
Helmut

**Comment by simonbrowndotje** [comment]
Thanks, I understand. This is primarily a client library for the Structurizr service though, and I don't really want any changes to the core classes - having tags on the RelationshipView class is going to potentially confuse people who are using the Structurizr service, which doesn't support this concept.

**Comment by kirchsth** [comment]
Hi Simon, 
**1. properties are fine** I will update my implementation (remove all tags; and add to the Relationship Property["PUML_DefaultLayout"]; and to the RelationshipView property ["PUML_Layout"].
**2.** during my C4-PlantUML pull request, details see https://github.com/RicardoNiepel/C4-PlantUML/pull/34 it starts a discussion about "Container" or "ContainerInstance", In your current model you store only health check urls and no "productive" url/endpoint. 
Can you suggest a property which should be displayed?
Thank you
Hemut

**Comment by simonbrowndotje** [comment]
Thanks. I'm not sure what you mean by, "In your current model you store only health check urls and no "productive" url/endpoint. Can you suggest a property which should be displayed?" ... could you elaborate?

**Comment by kirchsth** [comment]
In my branch https://github.com/kirchsth/C4-PlantUML I have a hypothetical sample with tenants, and both are children of the same node (and in your case both would have a different health check url). 
(I found a bug in my sample: both should have the same description "Stores Tenant related information")
I know database is not a good health check sample but I think it explains the idea.

**Comment by simonbrowndotje** [comment]
Yes, I think you're correct on both counts...

- Each database should be labelled "Stores Tenant related information".
- Each database instance would have a different health check URL. I wouldn't necessarily add this to the diagram though, I certainly don't with Structurizr.

**Comment by kirchsth** [comment]
Following your current pattern with the FailoverTag, then your solution could look like: 
a) the diagram would display one "Tenant" OK and the other "Tenant" NotOK
b) and each tenant has it own Tag (instead of "FailoverTag", "Tenant1Tag" and "Tenant2Tag")
c) and the diagram uses e.g. 2 different (style based) colors
d) and the user knows which "Tenant" is failing 
Is my assumption correct?

**Comment by simonbrowndotje** [comment]
It's really up to you, and it can be visualised however you like, there are no "rules" here. For the Structurizr service, the colour of the container instance is changed based upon the health check passing (e.g. https://structurizr.com/share/38000/health) ... but I don't think many people use this feature to be honest. It's also worth noting that this is a dynamic diagram, not a static image.

**Comment by kirchsth** [comment]
I agree, it is a static diagram. I used the "different health check urls" only to demonstrate that there could be different instances in one node and a user cannot distinguish between the 2 instances (except the different displayed relationships which have different descriptions)

**Comment by kirchsth** [comment]
Hi Simon, 
all my changes are in. Can you please review it?  I hope you like it.
Best regards
Helmut

**Comment by kirchsth** [comment]
@simonbrowndotje: do I have to make something special that state "Changes requested" is changed?

**Comment by simonbrowndotje** [comment]
Thanks very much ... I'm travelling at the moment, but this is on my todo list for next week when I get back home.

**Pull request merged**
