### PR TITLE
Fixes: #75 - HttpClient shouldn't be disposed all the time

### PR DESCRIPTION
**Pull request by MirzaMerdovic**
Changes:
- Added constructor overload that accepts HttpClient instance
- Put a lock around createHttpClient method so it always returns the same HttpClient instance
- Added some tests to cover new constructor and concurrency scenario

### CODE REVIEW

**Comment by simonbrowndotje** [comment]
Thanks. Wouldn't it just be easier to create an instance of HttpClient (inside StructurizrClient), when the StructurizrClient instance is created, and just reuse this instance in the get/put/lock/unlock methods? I can see the additional constructor causing confusion too.

**Comment by MirzaMerdovic** [comment]
Thanks for looking into my PR and for the feedback.

I added the additional constructor for the case where people would want to inject the HttpClient themselves via DI or manually.
They have an option to override `createHttpClient` method, but that implies that you need to implement an extra class that will inherit `StructurizrClient`. 
I would personally remove the `createHttpClient` method and leave the constructor, but that would be a breaking change, but I see you point of view as well, so if you want the constructor removed I will update the PR.

**Comment by MirzaMerdovic** [comment]
Additional constructor has been removed now `createHttpClient` method is the sole controller of HttpClient instance lifecycle.

**Comment by simonbrowndotje** [comment]
Thanks again. To provide some background, the extensions project has a subclass of `StructurizrClient` that sets some additional properties in an overridden version of the `createHttpClient` method ([AzureActiveDirectoryStructurizrClient](https://github.com/structurizr/dotnet-extensions/blob/master/Structurizr.ActiveDirectory/AzureActiveDirectoryStructurizrClient.cs#L39)).

Looking at the [docs for HttpClient](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=net-5.0#remarks), it says that the various Get/Put/Post methods are thread-safe, but `Properties of HttpClient should not be modified while there are outstanding requests, because it is not thread-safe`. So the changes in the PR are now prone to concurrency errors, because the [`AddHeaders` method ](https://github.com/structurizr/dotnet/blob/4ac300b5e7e923355e1cb9beb686b27e3fbd6255/Structurizr.Client/Api/StructurizrClient.cs#L319) is setting properties on the shared instance.

This is all fixable, but unless you are experiencing port exhaustion issues yourself during usage, I'm going to suggest that we just leave all this as-is, and close the issue + PR. In most usage, people are going to start their Structurizr program, lock, get, put and unlock the workspace, before the program ends ... i.e. this isn't a long-lived process, so port exhaustion  isn't likely an issue.

**Comment by MirzaMerdovic** [comment]
Makes sense. Closing this one then, thanks for the feedback and the time!

**Comment by simonbrowndotje** [comment]
Likewise!

**Pull request closed without merging**
